package com.flashcards_8.Utilidades;

import com.flashcards_8.Entidades.Palabra;
import java.util.ArrayList;
import java.util.List;

public class GeneradorDePalabras {
    public static List<Palabra> generarListaDePalabras() {
        List<Palabra> palabras = new ArrayList<>();
            palabras.add(new Palabra(1, "Agua", "android.resource://com.flashcards_8/raw/agua", "android.resource://com.flashcards_8/raw/aguaa", 1));
            palabras.add(new Palabra(2, "Bebé", "android.resource://com.flashcards_8/raw/bebe", "android.resource://com.flashcards_8/raw/bebea", 1));
            palabras.add(new Palabra(3, "Bici", "android.resource://com.flashcards_8/raw/bici", "android.resource://com.flashcards_8/raw/bicia", 1));
            palabras.add(new Palabra(4, "Boca", "android.resource://com.flashcards_8/raw/boca", "android.resource://com.flashcards_8/raw/bocaa", 1));
            palabras.add(new Palabra(5, "Bota", "android.resource://com.flashcards_8/raw/bota", "android.resource://com.flashcards_8/raw/botaa", 1));
            palabras.add(new Palabra(6, "Cama", "android.resource://com.flashcards_8/raw/cama", "android.resource://com.flashcards_8/raw/camaa", 1));
            palabras.add(new Palabra(7, "Café", "android.resource://com.flashcards_8/raw/cafe", "android.resource://com.flashcards_8/raw/cafea", 1));
            palabras.add(new Palabra(8, "Casa", "android.resource://com.flashcards_8/raw/casa", "android.resource://com.flashcards_8/raw/casaa", 1));
            palabras.add(new Palabra(9, "Coche", "android.resource://com.flashcards_8/raw/coche", "android.resource://com.flashcards_8/raw/cochea", 1));
            palabras.add(new Palabra(10, "Comer", "android.resource://com.flashcards_8/raw/comer", "android.resource://com.flashcards_8/raw/comera", 1));
            palabras.add(new Palabra(11, "Dado", "android.resource://com.flashcards_8/raw/dado", "android.resource://com.flashcards_8/raw/dadoa", 1));
            palabras.add(new Palabra(12, "Dedo", "android.resource://com.flashcards_8/raw/dedo", "android.resource://com.flashcards_8/raw/dedoa", 1));
            palabras.add(new Palabra(13, "Sucio", "android.resource://com.flashcards_8/raw/sucio", "android.resource://com.flashcards_8/raw/sucioa", 1));
            palabras.add(new Palabra(14, "Foca", "android.resource://com.flashcards_8/raw/foca", "android.resource://com.flashcards_8/raw/focaa", 1));
            palabras.add(new Palabra(15, "Galleta", "android.resource://com.flashcards_8/raw/galleta", "android.resource://com.flashcards_8/raw/galletaa", 1));
            palabras.add(new Palabra(16, "Gato", "android.resource://com.flashcards_8/raw/gato", "android.resource://com.flashcards_8/raw/gatoa", 1));
            palabras.add(new Palabra(17, "Grande", "android.resource://com.flashcards_8/raw/grande", "android.resource://com.flashcards_8/raw/grandea", 1));
            palabras.add(new Palabra(18, "Huevo", "android.resource://com.flashcards_8/raw/huevo", "android.resource://com.flashcards_8/raw/huevoa", 1));
            palabras.add(new Palabra(19, "Leche", "android.resource://com.flashcards_8/raw/leche", "android.resource://com.flashcards_8/raw/lechea", 1));
            palabras.add(new Palabra(20, "Luna", "android.resource://com.flashcards_8/raw/luna", "android.resource://com.flashcards_8/raw/lunaa", 1));
            palabras.add(new Palabra(21, "Llave", "android.resource://com.flashcards_8/raw/llave", "android.resource://com.flashcards_8/raw/llavea", 2));
            palabras.add(new Palabra(22, "Mamá", "android.resource://com.flashcards_8/raw/mama", "android.resource://com.flashcards_8/raw/mamaa", 2));
            palabras.add(new Palabra(23, "Mano", "android.resource://com.flashcards_8/raw/mano", "android.resource://com.flashcards_8/raw/manoa", 2));
            palabras.add(new Palabra(24, "Mesa", "android.resource://com.flashcards_8/raw/mesa", "android.resource://com.flashcards_8/raw/mesaa", 2));
            palabras.add(new Palabra(25, "Mirar", "android.resource://com.flashcards_8/raw/mirar", "android.resource://com.flashcards_8/raw/mirara", 2));
            palabras.add(new Palabra(26, "Moto", "android.resource://com.flashcards_8/raw/moto", "android.resource://com.flashcards_8/raw/motoa", 2));
            palabras.add(new Palabra(27, "Muñeca", "android.resource://com.flashcards_8/raw/muneca", "android.resource://com.flashcards_8/raw/munecaa", 2));
            palabras.add(new Palabra(28, "Niña", "android.resource://com.flashcards_8/raw/nina", "android.resource://com.flashcards_8/raw/ninaa", 2));
            palabras.add(new Palabra(29, "Niño", "android.resource://com.flashcards_8/raw/nino", "android.resource://com.flashcards_8/raw/ninoa", 2));
            palabras.add(new Palabra(30, "Ojo", "android.resource://com.flashcards_8/raw/ojo", "android.resource://com.flashcards_8/raw/ojoa", 2));
            palabras.add(new Palabra(31, "Oso", "android.resource://com.flashcards_8/raw/oso", "android.resource://com.flashcards_8/raw/osoa", 2));
            palabras.add(new Palabra(32, "Pan", "android.resource://com.flashcards_8/raw/pan", "android.resource://com.flashcards_8/raw/pana", 2));
            palabras.add(new Palabra(33, "Pez", "android.resource://com.flashcards_8/raw/pez", "android.resource://com.flashcards_8/raw/peza", 2));
            palabras.add(new Palabra(34, "Pie", "android.resource://com.flashcards_8/raw/pie", "android.resource://com.flashcards_8/raw/piea", 2));
            palabras.add(new Palabra(35, "Queso", "android.resource://com.flashcards_8/raw/queso", "android.resource://com.flashcards_8/raw/quesoa", 2));
            palabras.add(new Palabra(36, "Ratón", "android.resource://com.flashcards_8/raw/raton", "android.resource://com.flashcards_8/raw/ratona", 2));
            palabras.add(new Palabra(37, "Silla", "android.resource://com.flashcards_8/raw/silla", "android.resource://com.flashcards_8/raw/sillaa", 2));
            palabras.add(new Palabra(38, "Sol", "android.resource://com.flashcards_8/raw/sol", "android.resource://com.flashcards_8/raw/sola", 2));
            palabras.add(new Palabra(39, "Sopa", "android.resource://com.flashcards_8/raw/sopa", "android.resource://com.flashcards_8/raw/sopaa", 2));
            palabras.add(new Palabra(40, "Jugo", "android.resource://com.flashcards_8/raw/jugo", "android.resource://com.flashcards_8/raw/jugoa", 2));
            palabras.add(new Palabra(41, "Taza", "android.resource://com.flashcards_8/raw/taza", "android.resource://com.flashcards_8/raw/tazaa", 3));
            palabras.add(new Palabra(42, "Tele", "android.resource://com.flashcards_8/raw/tele", "android.resource://com.flashcards_8/raw/telea", 3));
            palabras.add(new Palabra(43, "Tocar", "android.resource://com.flashcards_8/raw/tocar", "android.resource://com.flashcards_8/raw/tocara", 3));
            palabras.add(new Palabra(44, "Tren", "android.resource://com.flashcards_8/raw/tren", "android.resource://com.flashcards_8/raw/trena", 3));
            palabras.add(new Palabra(45, "Uva", "android.resource://com.flashcards_8/raw/uva", "android.resource://com.flashcards_8/raw/uvaa", 3));
            palabras.add(new Palabra(46, "Vaca", "android.resource://com.flashcards_8/raw/vaca", "android.resource://com.flashcards_8/raw/vacaa", 3));
            palabras.add(new Palabra(47, "Vaso", "android.resource://com.flashcards_8/raw/vaso", "android.resource://com.flashcards_8/raw/vasoa", 3));
            palabras.add(new Palabra(48, "Zapato", "android.resource://com.flashcards_8/raw/zapato", "android.resource://com.flashcards_8/raw/zapatoa", 3));
            palabras.add(new Palabra(49, "Nido", "android.resource://com.flashcards_8/raw/nido", "android.resource://com.flashcards_8/raw/nidoa", 3));
            palabras.add(new Palabra(50, "Botella", "android.resource://com.flashcards_8/raw/botella", "android.resource://com.flashcards_8/raw/botellaa", 3));
            palabras.add(new Palabra(51, "Pala", "android.resource://com.flashcards_8/raw/pala", "android.resource://com.flashcards_8/raw/palaa", 3));
            palabras.add(new Palabra(52, "Papa", "android.resource://com.flashcards_8/raw/papa", "android.resource://com.flashcards_8/raw/papaa", 3));
            palabras.add(new Palabra(53, "Fresa", "android.resource://com.flashcards_8/raw/fresa", "android.resource://com.flashcards_8/raw/fresaa", 3));
            palabras.add(new Palabra(54, "Nudo", "android.resource://com.flashcards_8/raw/nudo", "android.resource://com.flashcards_8/raw/nudoa", 3));
            palabras.add(new Palabra(55, "Rojo", "android.resource://com.flashcards_8/raw/rojo", "android.resource://com.flashcards_8/raw/rojoa", 3));
            palabras.add(new Palabra(56, "Rosa", "android.resource://com.flashcards_8/raw/rosa", "android.resource://com.flashcards_8/raw/rosaa", 3));
            palabras.add(new Palabra(57, "Sala", "android.resource://com.flashcards_8/raw/sala", "android.resource://com.flashcards_8/raw/salaa", 3));
            palabras.add(new Palabra(58, "Azul", "android.resource://com.flashcards_8/raw/azul", "android.resource://com.flashcards_8/raw/azula", 3));
            palabras.add(new Palabra(59, "Amarillo", "android.resource://com.flashcards_8/raw/amarillo", "android.resource://com.flashcards_8/raw/amarilloa", 3));
            palabras.add(new Palabra(60, "Morado", "android.resource://com.flashcards_8/raw/morado", "android.resource://com.flashcards_8/raw/moradoa", 3));
        return palabras;
    }
}
